---
- name: Generate conscienceagent inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      conscienceagent:
        - id: "{{ namespace | d(default_namespace) }}-conscienceagent-{{ openio_conscienceagent_serviceid }}"
          ip: ""
          port: 0
          partition: ""
          volume: ""
          location: ""
          config: {}
  when:
    - "'conscience-agent' in group_names"
...
