---
- name: Generate namespace inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'config': {}, 'services': {} } } }, recursive=true) }}"
...
