---
- name: Generate oio-blob-rebuilder inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      oioblobrebuilder:
        - id: "{{ namespace | d(default_namespace) }}-oioblobrebuilder-{{ openio_blob_rebuilder_serviceid }}"
          ip: ""
          port: 0
          partition: ""
          volume: ""
          config: {}
  when:
    - "'oio-blob-rebuilder' in group_names"
...
