---
- name: Generate oioeventagent inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      oioeventagent:
        - id: "{{ namespace | d(default_namespace) }}-oioeventagent-{{ openio_event_agent_serviceid }}"
          ip: ""
          port: 0
          partition: ""
          volume: ""
          location: "{{ openio_event_agent_location }}"
          config: {}
  when:
    - "'oio-event-agent' in group_names"
...
