---
- name: Generate oioproxy inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      oioproxy:
        - id: "{{ namespace | d(default_namespace) }}-oioproxy-{{ openio_oioproxy_serviceid }}"
          ip: "{{ openio_oioproxy_bind_address }}"
          port: "{{ openio_oioproxy_bind_port }}"
          partition: ""
          volume: ""
          location: ""
          config: {}
  when:
    - "'oioproxy' in group_names"
...
