---
- name: Generate oioswift inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      oioswift:
        - id: "{{ namespace | d(default_namespace) }}-oioswift-{{ openio_oioswift_serviceid }}"
          ip: "{{ openio_oioswift_bind_address }}"
          port: "{{ openio_oioswift_bind_port }}"
          partition: ""
          volume: ""
          location: ""
          config: {}
  when:
    - "'oioswift' in group_names"
...
