---
- name: Generate zookeeper inventory
  set_fact:
    inventory: "{{ inventory | combine({ 'namespaces': { namespace | d(default_namespace): { 'services': new_item } } }, recursive=true) }}"
  vars:
    new_item:
      zookeeper:
        - id: "{{ namespace | d(default_namespace) }}-zookeeper-{{ openio_zookeeper_serviceid }}"
          ip: "{{ openio_zookeeper_bind_address }}"
          port: "{{ openio_zookeeper_bind_port  }}"
          partition: ""
          volume: "{{ openio_metadata_mounts[0]['mountpoint'] }}/{{ namespace | d(default_namespace) }}/zookeeper-{{ openio_zookeeper_serviceid }}"
          location: ""
          config: {}
  when:
    - openio_metadata_mounts is defined
    - "'zookeeper' in group_names"
...
