---
- name: Install and configure a Galera cluster 
  any_errors_fatal: true
  hosts: galera
  become : true
  gather_facts: true
  environment: "{{ openio_environment }}"
  pre_tasks:
    - name: set openio_bind_address as fact
      set_fact:
        openio_bind_address: "{{ openio_bind_address }}"

  roles:
    - role: galera
...
