---
- name: Caching facts
  hosts: openio:oiofs_ha:oiofs:admin
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false
  tags:
    - always
    - facts
    - fact
  vars_files:
    - vars/sds.yml

  tasks:
    - name: Install python
      raw: "test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)"
      changed_when: false
      check_mode: false
      become: true

    - name: Gather minimal facts
      setup:
        gather_subset: '!all,min'
        filter: '{{ item }}'
      when: hostvars[inventory_hostname][item] is not defined
      loop:
        - ansible_os_family
        - ansible_hostname
        - ansible_fqdn
        - ansible_distribution
        - ansible_distribution_release
        - ansible_architecture
        - ansible_system
        - ansible_selinux
        - ansible_service_mgr
        - ansible_distribution_major_version
        - ansible_distribution_version

    - name: Gather hardware facts
      setup:
        gather_subset: '!all,!min,hardware'
        filter: '{{ item }}'
      when: hostvars[inventory_hostname][item] is not defined
      loop:
        - ansible_memtotal_mb
        - ansible_processor_vcpus
        - ansible_devices
        - ansible_mounts

    - name: Gather static network facts
      setup:
        gather_subset: '!all,!min,network'
        filter: '{{ item }}'
      when: hostvars[inventory_hostname][item] is not defined
      loop:
        - ansible_default_ipv4
        - ansible_all_ipv4_addresses

    - name: Gather dynamic network facts
      setup:
        gather_subset: '!all,!min,network'
        filter: '{{ item }}'
      when: hostvars[inventory_hostname][item] is not defined
      vars:
        item: "{{ 'ansible_' ~ openio_bind_interface }}"

    - name: Gather virtual facts
      setup:
        gather_subset: '!all,!min,virtual'
        filter: '{{ item }}'
      when: hostvars[inventory_hostname][item] is not defined
      loop:
        - ansible_virtualization_type

    - name: Set custom facts
      set_fact:
        cacheable: true
        '{{ item.name }}': '{{ item.value }}'
      when: hostvars[inventory_hostname][item.name] is not defined
      loop:
        - name: openio_bind_address
          value: "{{ openio_bind_address | d(default_openio_bind_address) }}"
        - name: openio_bind_mgmt_interface
          value: "{{ openio_bind_mgmt_interface | d(openio_bind_interface) }}"
        - name: openio_bind_mgmt_address
          value: "{{ openio_bind_mgmt_address | d(openio_bind_address) }}"

- name: Checks
  import_playbook: playbooks/checks.yml
  tags:
    - checks
    - check

- name: Install base
  import_playbook: playbooks/install_basic_needs.yml
  tags: base

- name: SDS
  import_playbook: playbooks/openiosds.yml
  tags: sds

- name: Memcached
  import_playbook: playbooks/memcached.yml
  tags:
    - memcached
    - s3

- name: Swift
  import_playbook: playbooks/oioswift.yml
  tags:
    - swift
    - oioswift
    - s3

- name: Post install
  import_playbook: playbooks/postinstall.yml
  tags:
    - post
    - postinstall

- name: Inventory
  import_playbook: playbooks/inventory.yml
  tags: inventory
...
