---
- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: 4bded6650dd6801743bb7fc2deae336515264e4c
  name: repositories

- src: https://github.com/open-io/ansible-role-gridinit
  version: e168647c8e2ec02269e3138be880eb00952226ba
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-sds
  version: 06833959558482801eb6627c365f3d22a1a1fdfd
  name: openio-sds

- src: https://github.com/open-io/ansible-role-openio-netdata
  version: cc1fe69b3b71a440e8a1c0800493d3dfe7bb3138
  name: netdata

- src: https://github.com/open-io/ansible-role-openio-memcached
  version: 6e6df72a43a866dc71ba3492bfc8431afa57c419
  name: memcached

- src: https://github.com/open-io/ansible-role-openio-oioswift.git
  version: b7bc199a7c724712b69d3eaa25a37c658ff191a2
  name: oioswift

- src: https://github.com/open-io/ansible-role-openio-ecd.git
  version: 057097610796eb675fdf1fc841e1d6acf557f974
  name: ecd

- src: https://github.com/open-io/ansible-role-openio-account.git
  version: bb35d53a7ae4044207242aff37ed61327ab4d69e
  name: account

- src: https://github.com/open-io/ansible-role-openio-zookeeper
  version: f48fa03a9a32aac08895afa7cba1a6d10883a6c9
  name: zookeeper

- src: https://github.com/open-io/ansible-role-openio-ntp.git
  version: 35cb949af93b0eb2e644dad464be817e72b792e6
  name: ntp
...
