---
# SDS
- name: gridinit
  src: https://github.com/open-io/ansible-role-gridinit.git
  version: 56956f8586f74dbfc09a664119c9d7c28a63d618
- name: account
  src: https://github.com/open-io/ansible-role-openio-account.git
  version: 2ceef8407d0fb46fe3e39c4058269e92c17fc04b
- name: beanstalkd
  src: https://github.com/open-io/ansible-role-openio-beanstalkd.git
  version: 0f34e61f876f1e28c86dc851e6ac57a10394c2f3
- name: conscience
  src: https://github.com/open-io/ansible-role-openio-conscience.git
  version: 9a004db8904be8c6ce823dbe76c78f28a92ec729
- name: conscienceagent
  src: https://github.com/open-io/ansible-role-openio-conscienceagent.git
  version: 7289dcedfa6652d12b02546310dece0927ac7a75
- name: ecd
  src: https://github.com/open-io/ansible-role-openio-ecd.git
  version: 3c7cbb16919153b2b54cdccca815da22aa879b5d
- name: memcached
  src: https://github.com/open-io/ansible-role-openio-memcached.git
  version: 5764a4fedd187d1a6ba586c3cf84ea57a41df820
- name: meta
  src: https://github.com/open-io/ansible-role-openio-meta.git
  version: 57fa7eba4396aa4ed0b88bc3265ccfc409f0a52d
- name: namespace
  src: https://github.com/open-io/ansible-role-openio-namespace.git
  version: 9a695589ed5635b045a9d9b6422af5c4bc6d5eb5
- name: ntp
  src: https://github.com/open-io/ansible-role-openio-ntp.git
  version: 9028ec9fed76f8cee63926967b3882ed878b108f
- name: oio-blob-indexer
  src: https://github.com/open-io/ansible-role-openio-oio-blob-indexer.git
  version: 538fffe3a64f0dcc1ea6c2cc4181fec7fea42916
- name: oio-blob-rebuilder
  src: https://github.com/open-io/ansible-role-openio-oio-blob-rebuilder.git
  version: 565cba4a74ef697ff92d9140f83c8785c75e7e21
- name: oio-event-agent
  src: https://github.com/open-io/ansible-role-openio-oio-event-agent.git
  version: ec7f1eeb1be808a45dd30e5db1ea8306eac3a06e
- name: oio-meta2-indexer
  src: https://github.com/open-io/ansible-role-openio-oio-meta2-indexer.git
  version: e4f7204294535a83d4de872bf39e8e93dc23ee92
- name: oioproxy
  src: https://github.com/open-io/ansible-role-openio-oioproxy.git
  version: 58627a98733d413818a014f2097c36b6f1c78cb5
- name: oioswift
  src: https://github.com/open-io/ansible-role-openio-oioswift.git
  version: c928f7bf62d31238b13d4f5c9ecc71ccc1d945d4
- name: rawx
  src: https://github.com/open-io/ansible-role-openio-rawx.git
  version: 05208ad2fedcbd1e1ed22b1c883e6157be130e59
- name: rdir
  src: https://github.com/open-io/ansible-role-openio-rdir.git
  version: 271f27f2cc6f52604f428c552476cd209c2c2cc7
- name: redis
  src: https://github.com/open-io/ansible-role-openio-redis.git
  version: 2e82665154d2d04f58434f7ff684d59f01a46188
- name: repositories
  src: https://github.com/open-io/ansible-role-openio-repository.git
  version: 550c550d45c94d40bddcc12047f0f007bc3a3848
- name: users
  src: https://github.com/open-io/ansible-role-openio-users.git
  version: 4be2720b36adb3a2386ba04e188bbdf05d46a090
- name: xcute
  src: https://github.com/open-io/ansible-role-openio-xcute.git
  version: b78ae44475cbe3579935c583675f48dd9d5321de
- name: zookeeper
  src: https://github.com/open-io/ansible-role-openio-zookeeper.git
  version: f2a508d9178a39b4376043dce9a7a7bcc6e5c299

# OIOFS
- name: oiofs
  src: https://github.com/open-io/ansible-role-openio-oiofs.git
  version: 2a7e8e3e8d3dc2b717efc146775c53f0e9fd1152
- name: samba
  src: https://github.com/open-io/ansible-role-openio-samba.git
  version: 64c78e879a9ced727a23a2cf20c3668ad1fbf864
- name: nfs
  src: https://github.com/open-io/ansible-role-openio-nfs.git
  version: 6a15018f4ed1aac8e8573ce93e0e790dcf840d12
...
