---
openio_account_bind_address: "{{ openio_bind_address }}"
openio_account_sentinels_hosts: "{{ groups['openio_redis_cluster'] \
  | map('extract', hostvars, ['openio_bind_address']) \
    | join(':6012,') }}:6012"
...
